# Site
repository: duongt3/modern-resume-theme (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Timothy Duong
title: Systems Engineer
email: tmdng7@gmail.com
# email_title: Email (Email title override)
phone: 732-567-5804 (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Profile # (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Professional Systems Engineer with industry experience and currently pursuing a M.S. in Electrical and Computer Engineering with a focus in machine learning. 
  Expert grasp of engineering design cycle from ConOps, initial design studies, risk mitigation/design optimization, writing requirements, to testing and evaluation.
  Leadership and collaborative working with different business areas within Lockheed and with competitors on a government contract. Strong software skills from developing
  and maintaining our simulation

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: VDP
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Lockheed Martin
        sub_title: Systems Engineer
        caption: May 2018 - Present
        link: https://www.lockheedmartin.com/en-us/index.html
#         quote: >
#           Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Rowan University
        sub_title: M.S. Electrical and Computer Engineering
        caption: 2020 - 2022
        description: | # this will include new lines to allow paragraphs
          Description of qualification
      - layout: top-right
        title: Rowan University
        sub_title: B.S. Electrical and Computer Engineering 
        caption: 2016 - 2020
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: Skills and Proficiency
    layout: list
    content: |
      - "Machine Learning Frameworks: PyTorch, Sklearn, Keras, Tensorflow"
      - "Programming Languages: Python, C++, Java"
      - 
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
